language: objective-c
xcode_workspace: Project/CocoaOnePExample.xcworkspace
xcode_scheme: CocoaOnePExample
before_install:
    - brew update
    - brew upgrade xctool
    - export LANG=en_US.UTF-8
    - sudo gem install --no-document cocoapods
install:
    - xctool --version
    - cd Project
    - pod install
script: xctool -workspace CocoaOnePExample.xcworkspace -scheme CocoaOnePExample -sdk iphonesimulator8.0 test
notifications:
  email:
    - miketilstra@exosite.com

