language: objective-c
xcode_workspace: Project/CocoaOnePExample.xcworkspace
xcode_scheme: CocoaOnePExample
install:
    - cd Project
    - export LANG=en_US.UTF-8
    - sudo gem install --no-document cocoapods
    - pod install
script: xctool -workspace CocoaOnePExample.xcworkspace -scheme CocoaOnePExample -sdk iphonesimulator7.1 build test
notifications:
  email:
    - miketilstra@exosite.com

